<a href="https://colab.research.google.com/github/Radiant19/Blog-Website/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Pytorh Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.10.0+cu128


Introduction to Tensors

Creating sensors

In [3]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([1,1])
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[1,1],[2,2]])
MATRIX

tensor([[1, 1],
        [2, 2]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3,4],[4,5,6,4],[7,8,9,5],[9,8,7,8],[1,2,3,4]],[[1,2,3,4],[4,5,6,4],[7,8,9,5],[9,8,7,8],[1,2,3,4]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 5],
         [9, 8, 7, 8],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 5],
         [9, 8, 7, 8],
         [1, 2, 3, 4]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 5, 4])

In [15]:
TENSOR[0]

tensor([[1, 2, 3, 4],
        [4, 5, 6, 4],
        [7, 8, 9, 5],
        [9, 8, 7, 8],
        [1, 2, 3, 4]])

Random tensors

# Why random Tensor

Random tensors are important because the way nueral network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represnt the data

Start with random numbers -> look at the data -> update random numbers -> look at data -> update random numbers

In [16]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1533, 0.0051, 0.8556, 0.2690],
        [0.1401, 0.8830, 0.9425, 0.8987],
        [0.6255, 0.9803, 0.6414, 0.7049]])

In [17]:
#Create a random tensors with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channel,height,width
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [18]:
rand_tensor = torch.rand(4,2,2)
rand_tensor

tensor([[[0.7793, 0.5524],
         [0.2670, 0.7494]],

        [[0.3535, 0.9907],
         [0.2089, 0.4158]],

        [[0.4187, 0.1120],
         [0.6437, 0.3515]],

        [[0.7245, 0.3021],
         [0.2575, 0.0061]]])

Zeros and Ones

In [19]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#Crete a twnsors of ones

torch.ones(size=(3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
zeros.dtype

torch.float32

Range

In [22]:
# Create a range of tensors and tensors like
one_to_ten=torch.arange(start= 1,end=10,step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#Creatig tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes
Note
-Tensor datatype is one of the 3 big error you will run into with Pytorch and deeplearning
-Tensors not right datatype
-tensors not right shape
-tensors not on the right device

In [24]:
float_tensors = torch.tensor([3.,6.,9,],
                             dtype=None, # what datatpe is the tensor float 32? or float16
                             device=None, # What device the tensor is on
                             requires_grad=False) # #ehrther or not to track gradients with this tensor operation
float_tensors.dtype

torch.float32

In [25]:
float_16_tensor = float_tensors.type(torch.float16)
float_tensors.dtype

torch.float32

In [26]:
float_tensors

tensor([3., 6., 9.])

In [27]:
float_tensors * float_16_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3,6,9],dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [29]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

Getting Info from tensors / tensor attributes - datatypes,shape,device

In [30]:
some_tensor = torch.rand(3,4)

In [31]:
some_tensor

tensor([[0.3164, 0.0735, 0.5579, 0.7100],
        [0.5529, 0.2308, 0.7236, 0.4222],
        [0.6020, 0.3108, 0.6994, 0.2114]])

In [32]:
some_tensor.size()

torch.Size([3, 4])

In [33]:
#detils
print(some_tensor)
print(f"Datatypes {some_tensor.dtype}")
print(f"Shape {some_tensor.shape}")
print(f"Device on {some_tensor.device}")

tensor([[0.3164, 0.0735, 0.5579, 0.7100],
        [0.5529, 0.2308, 0.7236, 0.4222],
        [0.6020, 0.3108, 0.6994, 0.2114]])
Datatypes torch.float32
Shape torch.Size([3, 4])
Device on cpu


 Manipulating Tensors( Tensor Operations)

 Tensor operation inculde:
 - addition
 - subtraction
 - Multiplication (element wise)
 - Division
 - Matrix multiplication

In [34]:
#Create a tensor
tensor = torch.tensor([1,2,3])
#Adding 10 to it
tensor + 10

tensor([11, 12, 13])

In [35]:
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor

tensor([1, 2, 3])

In [37]:
tensor - 10

tensor([-9, -8, -7])

In [38]:
# Try out torch in-built function
torch.mul(tensor,10)

tensor([10, 20, 30])

Two main ways of performing multiplication in NN and Dl

1. Element-wise multiplication
2. Matirx multiplication (dot product)

There are two main rules that performing matrix mul need tos satift

1 Inner dimension must match:
- (3,2) @ (3,2) wont work
- (3,2) @ (2,3) will work
- (2,3) @ (3,2) will work

the resulting shape is outer dimension:
- (2,3) @ (3,2) -> (2,2)

In [39]:

torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.3168, 0.4436],
        [0.9598, 0.3266]])

In [40]:
tensor

tensor([1, 2, 3])

In [41]:
print(tensor, "*",tensor)
tensor * tensor

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor([1, 4, 9])

In [42]:
#Mat mul
%%time
torch.matmul(tensor,tensor)

CPU times: user 207 µs, sys: 33 µs, total: 240 µs
Wall time: 1.83 ms


tensor(14)

In [43]:
# Matrix multi by hand
1*1+2*2+3*3


14

In [44]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.17 ms, sys: 0 ns, total: 1.17 ms
Wall time: 3.24 ms


One of the most common error in Deep Learning

In [45]:
tensor_A = torch.tensor([[1,4],
                         [2,5],
                         [3,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [47]:
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [49]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [50]:
#the operation works when tensor_b is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shape : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}\n")
result  = torch.matmul(tensor_A,tensor_B.T)
print(result,result.shape)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shape : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])

tensor([[47, 52, 57],
        [64, 71, 78],
        [81, 90, 99]]) torch.Size([3, 3])


Tensor Aggregation - FIndind min max mean sum

In [51]:
x = torch.arange(0,100,10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [52]:
torch.max(x)

tensor(90)

In [53]:
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [54]:
# Find the mean - note the torch.mean() func require a tensor of flat32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [55]:
x.sum()

tensor(450)

Finding position of MAx and MIn

In [56]:
torch.argmin(x),torch.argmax(x)

(tensor(0), tensor(9))

In [57]:
x[0] , x[9]

(tensor(0), tensor(90))

Reshape, Stacking, squeezing and unsqueezing tensors:
- Reshaping - reshapes an input tensors to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as original tensor
- Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all 1 dimension from tensor
- unsqueeze - add 1 dimension to a target tensor
- permute- return a view of the input with dimension permuted(swapped) in a certain way

In [58]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
x_reshaped1 = x.reshape(3,3)
x_reshaped1, x_reshaped1.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [61]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
#Changing z will change x as they sahre the same memory
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [63]:
#Stack tensors on top of each other

x_shacked = torch.stack([x,x,x,x],dim=0)
x_shacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [64]:
#Squeeze and Unqueeze
x_reshaped , x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# torch.squeeze - removes all the single dimension from the target tensor
# The variable x_reshaped is currently a tuple due to a previous assignment.
# We need to extract the tensor from the tuple first.

x_squeezed = x_reshaped.squeeze()
x_squeezed , x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [66]:
#torch.unqueeze = add a single dimension to a target tensor at a specific dimension
x_squeezed.unsqueeze(dim=0), x_squeezed.unsqueeze(dim=0).shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
#torch.permute - allows you to reaaranges  the dimension in a specified order
x_original = torch.rand(size=(224,224,3))

x_permute = x_original.permute(2,0,1)
x_original.shape, x_permute.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [68]:
x_permute[0,0,0]=0
x_original[0,0,0]

tensor(0.)

**Indexing (selecting data from tensors)**

Indexing with Pytorch is similar to indexing with Numpy

In [69]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [70]:
#Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [71]:
x[0,0] , x[0,0,0]

(tensor([1, 2, 3]), tensor(1))

In [72]:
x[0][1]

tensor([4, 5, 6])

In [73]:
x[0][2][2]

tensor(9)

In [74]:
# You can also you ":" to select "ALL" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [75]:
#Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [76]:
#Get aa values of 0th dimension but 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [77]:
# Get index 0 of 0th and first dimension and all values of 2nd dimension

x[0,2,:]

tensor([7, 8, 9])

In [78]:
#Index on x to return 9
x[:,2,2]
#Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

#PyTorch tensors and numPy

Numpy is a popular scientific Python numerical computing library

and because of this, Pytorch has functionality to interact with it:
- Data in NumPy, want in Pytorch tensor -> torch.from_numpy(ndarray)
- Pytorch tensor -> Numpy -> torch.Tensor.numpy()

In [79]:
import numpy as np

array = np.arange(1.0,8.0) #default when covert array to tensor the type will be float64(default of numpy array) but the defaults of tensor is float32
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [80]:
#Chnage array and check for  any change in tensor
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [81]:
 #tensor to array
 tensor = torch.ones(7)
 numpy_tensor = tensor.numpy()
 tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [82]:
tensor  = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility (trying to take random out of random)

In short how nn learns:

`start with random numbers -> tensor operations -> update random no to try and make them better representation of data again agian and again`

To reduce the randomnees in nural network and pytorch comes the concepy of random seed

essential what the seed does is'flavour' the randomness

In [83]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5382, 0.4039, 0.3650, 0.5023],
        [0.4320, 0.0043, 0.7955, 0.3387],
        [0.4885, 0.7032, 0.5565, 0.2520]])
tensor([[0.5312, 0.0339, 0.2203, 0.9289],
        [0.0819, 0.6091, 0.8470, 0.9759],
        [0.2112, 0.5676, 0.2045, 0.9937]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [84]:
#Using Seed produce reproducible tensor

Random_Seed = 42
torch.manual_seed(Random_Seed)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(Random_Seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running tensors, models, Pytorch objects on the GPUs (makes computation faster)

TO run on GPU if available els on cpu

In [90]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [91]:
tensor = torch.tensor([1,2,3])
#Tensor not on gpu
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [92]:
# Move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

**Moving tensor back to CPU**

In [93]:
#If on gpu, can covert it to numpy
tensor_on_gpu.numpy()


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [94]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])